class StageRule {
  const StageRule({
    required this.stage,
    required this.name,
    required this.playerSpeedMultiplier,
    required this.baseFlipInterval,
    required this.flipRandomnessMin,
    required this.flipRandomnessMax,
    required this.firstFlipDelay,
    required this.warningTime,
    required this.mazeSize,
    required this.devilEnabled,
    required this.devilSpeedMultiplier,
    required this.devilSpawnDelay,
    required this.devilStepsPerSecond,
    required this.devilSpawnDistanceCells,
    required this.safeZoneCount,
    required this.safeZoneDurationSeconds,
  });

  final int stage;
  final String name;
  final double playerSpeedMultiplier;
  final double baseFlipInterval;
  final double flipRandomnessMin;
  final double flipRandomnessMax;
  final double firstFlipDelay;
  final double warningTime;
  final int mazeSize;
  final bool devilEnabled;
  final double devilSpeedMultiplier;
  final double devilSpawnDelay;
  final double devilStepsPerSecond;
  final int devilSpawnDistanceCells;
  final int safeZoneCount;
  final double safeZoneDurationSeconds;
}

class StageRules {
  static const int maxDefinedStage = 100;
  static const double _devilPlayerSpeedDelta = 0.01;

  static const Map<int, StageRule> _rules = <int, StageRule>{
    1: StageRule(
      stage: 1,
      name: 'Awakening',
      playerSpeedMultiplier: 1.0,
      baseFlipInterval: 5.0,
      flipRandomnessMin: 0.0,
      flipRandomnessMax: 0.0,
      firstFlipDelay: 4.0,
      warningTime: 1.2,
      mazeSize: 10,
      devilEnabled: true,
      devilSpeedMultiplier: 0.99,
      devilSpawnDelay: 8.0,
      devilStepsPerSecond: 0.35,
      devilSpawnDistanceCells: 9,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 3.0,
    ),
    2: StageRule(
      stage: 2,
      name: 'Inversion',
      playerSpeedMultiplier: 1.0,
      baseFlipInterval: 5.0,
      flipRandomnessMin: 0.0,
      flipRandomnessMax: 0.0,
      firstFlipDelay: 3.0,
      warningTime: 1.0,
      mazeSize: 11,
      devilEnabled: true,
      devilSpeedMultiplier: 0.99,
      devilSpawnDelay: 7.0,
      devilStepsPerSecond: 0.45,
      devilSpawnDistanceCells: 8,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 2.5,
    ),
    3: StageRule(
      stage: 3,
      name: 'Control',
      playerSpeedMultiplier: 1.05,
      baseFlipInterval: 5.0,
      flipRandomnessMin: 0.10,
      flipRandomnessMax: 0.20,
      firstFlipDelay: 3.0,
      warningTime: 0.9,
      mazeSize: 12,
      devilEnabled: true,
      devilSpeedMultiplier: 1.04,
      devilSpawnDelay: 6.0,
      devilStepsPerSecond: 0.55,
      devilSpawnDistanceCells: 8,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 2.0,
    ),
    4: StageRule(
      stage: 4,
      name: 'Distortion',
      playerSpeedMultiplier: 1.05,
      baseFlipInterval: 4.5,
      flipRandomnessMin: 0.20,
      flipRandomnessMax: 0.30,
      firstFlipDelay: 2.5,
      warningTime: 0.8,
      mazeSize: 13,
      devilEnabled: true,
      devilSpeedMultiplier: 1.04,
      devilSpawnDelay: 5.5,
      devilStepsPerSecond: 0.65,
      devilSpawnDistanceCells: 7,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 2.0,
    ),
    5: StageRule(
      stage: 5,
      name: 'First Contact',
      playerSpeedMultiplier: 1.08,
      baseFlipInterval: 4.0,
      flipRandomnessMin: 0.20,
      flipRandomnessMax: 0.30,
      firstFlipDelay: 2.5,
      warningTime: 0.8,
      mazeSize: 14,
      devilEnabled: true,
      devilSpeedMultiplier: 0.60,
      devilSpawnDelay: 5.0,
      devilStepsPerSecond: 0.75,
      devilSpawnDistanceCells: 7,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 1.5,
    ),
    6: StageRule(
      stage: 6,
      name: 'Pursuit',
      playerSpeedMultiplier: 1.08,
      baseFlipInterval: 4.0,
      flipRandomnessMin: 0.25,
      flipRandomnessMax: 0.25,
      firstFlipDelay: 2.5,
      warningTime: 0.8,
      mazeSize: 15,
      devilEnabled: true,
      devilSpeedMultiplier: 0.70,
      devilSpawnDelay: 3.0,
      devilStepsPerSecond: 0.85,
      devilSpawnDistanceCells: 6,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 1.2,
    ),
    7: StageRule(
      stage: 7,
      name: 'Decisions',
      playerSpeedMultiplier: 1.10,
      baseFlipInterval: 3.8,
      flipRandomnessMin: 0.30,
      flipRandomnessMax: 0.30,
      firstFlipDelay: 2.5,
      warningTime: 0.7,
      mazeSize: 16,
      devilEnabled: true,
      devilSpeedMultiplier: 0.75,
      devilSpawnDelay: 3.0,
      devilStepsPerSecond: 0.95,
      devilSpawnDistanceCells: 5,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 1.0,
    ),
    8: StageRule(
      stage: 8,
      name: 'Acceleration',
      playerSpeedMultiplier: 1.12,
      baseFlipInterval: 3.5,
      flipRandomnessMin: 0.35,
      flipRandomnessMax: 0.35,
      firstFlipDelay: 2.2,
      warningTime: 0.7,
      mazeSize: 17,
      devilEnabled: true,
      devilSpeedMultiplier: 0.80,
      devilSpawnDelay: 2.5,
      devilStepsPerSecond: 1.05,
      devilSpawnDistanceCells: 4,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.8,
    ),
    9: StageRule(
      stage: 9,
      name: 'Instability',
      playerSpeedMultiplier: 1.12,
      baseFlipInterval: 3.5,
      flipRandomnessMin: 0.40,
      flipRandomnessMax: 0.40,
      firstFlipDelay: 2.2,
      warningTime: 0.6,
      mazeSize: 18,
      devilEnabled: true,
      devilSpeedMultiplier: 0.85,
      devilSpawnDelay: 2.5,
      devilStepsPerSecond: 1.15,
      devilSpawnDistanceCells: 4,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.7,
    ),
    10: StageRule(
      stage: 10,
      name: 'Trial',
      playerSpeedMultiplier: 1.15,
      baseFlipInterval: 3.25,
      flipRandomnessMin: 0.45,
      flipRandomnessMax: 0.45,
      firstFlipDelay: 2.0,
      warningTime: 0.6,
      mazeSize: 19,
      devilEnabled: true,
      devilSpeedMultiplier: 0.90,
      devilSpawnDelay: 2.0,
      devilStepsPerSecond: 1.30,
      devilSpawnDistanceCells: 3,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.5,
    ),
    11: StageRule(
      stage: 11,
      name: 'Disturbance',
      playerSpeedMultiplier: 1.15,
      baseFlipInterval: 3.25,
      flipRandomnessMin: 0.45,
      flipRandomnessMax: 0.45,
      firstFlipDelay: 2.0,
      warningTime: 0.6,
      mazeSize: 19,
      devilEnabled: true,
      devilSpeedMultiplier: 0.92,
      devilSpawnDelay: 2.0,
      devilStepsPerSecond: 1.35,
      devilSpawnDistanceCells: 3,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.5,
    ),
    12: StageRule(
      stage: 12,
      name: 'Split Mind',
      playerSpeedMultiplier: 1.16,
      baseFlipInterval: 3.2,
      flipRandomnessMin: 0.50,
      flipRandomnessMax: 0.50,
      firstFlipDelay: 2.0,
      warningTime: 0.6,
      mazeSize: 20,
      devilEnabled: true,
      devilSpeedMultiplier: 0.95,
      devilSpawnDelay: 2.0,
      devilStepsPerSecond: 1.40,
      devilSpawnDistanceCells: 3,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.4,
    ),
    13: StageRule(
      stage: 13,
      name: 'Deception',
      playerSpeedMultiplier: 1.17,
      baseFlipInterval: 3.05,
      flipRandomnessMin: 0.50,
      flipRandomnessMax: 0.50,
      firstFlipDelay: 1.8,
      warningTime: 0.5,
      mazeSize: 20,
      devilEnabled: true,
      devilSpeedMultiplier: 1.0,
      devilSpawnDelay: 1.8,
      devilStepsPerSecond: 1.50,
      devilSpawnDistanceCells: 3,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    14: StageRule(
      stage: 14,
      name: 'Instability',
      playerSpeedMultiplier: 1.18,
      baseFlipInterval: 2.95,
      flipRandomnessMin: 0.55,
      flipRandomnessMax: 0.55,
      firstFlipDelay: 1.8,
      warningTime: 0.5,
      mazeSize: 21,
      devilEnabled: true,
      devilSpeedMultiplier: 1.05,
      devilSpawnDelay: 1.8,
      devilStepsPerSecond: 1.60,
      devilSpawnDistanceCells: 2,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    15: StageRule(
      stage: 15,
      name: 'Instability Peak',
      playerSpeedMultiplier: 1.20,
      baseFlipInterval: 2.8,
      flipRandomnessMin: 0.55,
      flipRandomnessMax: 0.55,
      firstFlipDelay: 1.5,
      warningTime: 0.5,
      mazeSize: 21,
      devilEnabled: true,
      devilSpeedMultiplier: 1.08,
      devilSpawnDelay: 1.5,
      devilStepsPerSecond: 1.68,
      devilSpawnDistanceCells: 2,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    16: StageRule(
      stage: 16,
      name: 'Stabilization',
      playerSpeedMultiplier: 1.18,
      baseFlipInterval: 3.25,
      flipRandomnessMin: 0.40,
      flipRandomnessMax: 0.40,
      firstFlipDelay: 2.2,
      warningTime: 0.6,
      mazeSize: 20,
      devilEnabled: true,
      devilSpeedMultiplier: 1.0,
      devilSpawnDelay: 3.0,
      devilStepsPerSecond: 1.50,
      devilSpawnDistanceCells: 5,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 1.5,
    ),
    17: StageRule(
      stage: 17,
      name: 'Re-engage',
      playerSpeedMultiplier: 1.20,
      baseFlipInterval: 3.0,
      flipRandomnessMin: 0.45,
      flipRandomnessMax: 0.45,
      firstFlipDelay: 2.0,
      warningTime: 0.6,
      mazeSize: 21,
      devilEnabled: true,
      devilSpeedMultiplier: 1.05,
      devilSpawnDelay: 2.5,
      devilStepsPerSecond: 1.58,
      devilSpawnDistanceCells: 4,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 1.0,
    ),
    18: StageRule(
      stage: 18,
      name: 'Disruption',
      playerSpeedMultiplier: 1.22,
      baseFlipInterval: 2.85,
      flipRandomnessMin: 0.50,
      flipRandomnessMax: 0.50,
      firstFlipDelay: 2.0,
      warningTime: 0.5,
      mazeSize: 21,
      devilEnabled: true,
      devilSpeedMultiplier: 1.08,
      devilSpawnDelay: 2.2,
      devilStepsPerSecond: 1.65,
      devilSpawnDistanceCells: 3,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    19: StageRule(
      stage: 19,
      name: 'Compression',
      playerSpeedMultiplier: 1.22,
      baseFlipInterval: 2.65,
      flipRandomnessMin: 0.55,
      flipRandomnessMax: 0.55,
      firstFlipDelay: 1.9,
      warningTime: 0.5,
      mazeSize: 22,
      devilEnabled: true,
      devilSpeedMultiplier: 1.12,
      devilSpawnDelay: 2.0,
      devilStepsPerSecond: 1.72,
      devilSpawnDistanceCells: 3,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    20: StageRule(
      stage: 20,
      name: 'Chaos Entry',
      playerSpeedMultiplier: 1.25,
      baseFlipInterval: 2.55,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.8,
      warningTime: 0.5,
      mazeSize: 22,
      devilEnabled: true,
      devilSpeedMultiplier: 1.15,
      devilSpawnDelay: 1.8,
      devilStepsPerSecond: 1.80,
      devilSpawnDistanceCells: 2,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    21: StageRule(
      stage: 21,
      name: 'Overload Begins',
      playerSpeedMultiplier: 1.25,
      baseFlipInterval: 2.45,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.8,
      warningTime: 0.5,
      mazeSize: 22,
      devilEnabled: true,
      devilSpeedMultiplier: 1.18,
      devilSpawnDelay: 1.8,
      devilStepsPerSecond: 1.86,
      devilSpawnDistanceCells: 2,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    22: StageRule(
      stage: 22,
      name: 'Instability Surge',
      playerSpeedMultiplier: 1.27,
      baseFlipInterval: 2.35,
      flipRandomnessMin: 0.65,
      flipRandomnessMax: 0.65,
      firstFlipDelay: 1.6,
      warningTime: 0.45,
      mazeSize: 22,
      devilEnabled: true,
      devilSpeedMultiplier: 1.20,
      devilSpawnDelay: 1.6,
      devilStepsPerSecond: 1.93,
      devilSpawnDistanceCells: 2,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    23: StageRule(
      stage: 23,
      name: 'Mental Break',
      playerSpeedMultiplier: 1.28,
      baseFlipInterval: 2.25,
      flipRandomnessMin: 0.70,
      flipRandomnessMax: 0.70,
      firstFlipDelay: 1.5,
      warningTime: 0.45,
      mazeSize: 22,
      devilEnabled: true,
      devilSpeedMultiplier: 1.22,
      devilSpawnDelay: 1.5,
      devilStepsPerSecond: 2.0,
      devilSpawnDistanceCells: 2,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    24: StageRule(
      stage: 24,
      name: 'Final Stretch',
      playerSpeedMultiplier: 1.30,
      baseFlipInterval: 2.15,
      flipRandomnessMin: 0.75,
      flipRandomnessMax: 0.75,
      firstFlipDelay: 1.5,
      warningTime: 0.4,
      mazeSize: 22,
      devilEnabled: true,
      devilSpeedMultiplier: 1.25,
      devilSpawnDelay: 1.5,
      devilStepsPerSecond: 2.08,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    25: StageRule(
      stage: 25,
      name: 'Checkpoint Break',
      playerSpeedMultiplier: 1.28,
      baseFlipInterval: 2.75,
      flipRandomnessMin: 0.50,
      flipRandomnessMax: 0.50,
      firstFlipDelay: 3.0,
      warningTime: 0.6,
      mazeSize: 20,
      devilEnabled: true,
      devilSpeedMultiplier: 1.15,
      devilSpawnDelay: 3.0,
      devilStepsPerSecond: 1.60,
      devilSpawnDistanceCells: 5,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 1.5,
    ),
    26: StageRule(
      stage: 26,
      name: 'False Security',
      playerSpeedMultiplier: 1.30,
      baseFlipInterval: 2.55,
      flipRandomnessMin: 0.50,
      flipRandomnessMax: 0.50,
      firstFlipDelay: 2.4,
      warningTime: 0.55,
      mazeSize: 22,
      devilEnabled: true,
      devilSpeedMultiplier: 1.24,
      devilSpawnDelay: 2.4,
      devilStepsPerSecond: 2.15,
      devilSpawnDistanceCells: 2,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    27: StageRule(
      stage: 27,
      name: 'Tracking Shift',
      playerSpeedMultiplier: 1.32,
      baseFlipInterval: 2.45,
      flipRandomnessMin: 0.55,
      flipRandomnessMax: 0.55,
      firstFlipDelay: 2.2,
      warningTime: 0.52,
      mazeSize: 22,
      devilEnabled: true,
      devilSpeedMultiplier: 1.27,
      devilSpawnDelay: 2.2,
      devilStepsPerSecond: 2.22,
      devilSpawnDistanceCells: 2,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    28: StageRule(
      stage: 28,
      name: 'Shifted Reality',
      playerSpeedMultiplier: 1.34,
      baseFlipInterval: 2.35,
      flipRandomnessMin: 0.58,
      flipRandomnessMax: 0.58,
      firstFlipDelay: 2.0,
      warningTime: 0.50,
      mazeSize: 23,
      devilEnabled: true,
      devilSpeedMultiplier: 1.30,
      devilSpawnDelay: 2.0,
      devilStepsPerSecond: 2.30,
      devilSpawnDistanceCells: 2,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    29: StageRule(
      stage: 29,
      name: 'Pressure Loop',
      playerSpeedMultiplier: 1.35,
      baseFlipInterval: 2.25,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.9,
      warningTime: 0.48,
      mazeSize: 23,
      devilEnabled: true,
      devilSpeedMultiplier: 1.31,
      devilSpawnDelay: 1.9,
      devilStepsPerSecond: 2.36,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    30: StageRule(
      stage: 30,
      name: 'Collapse Entry',
      playerSpeedMultiplier: 1.36,
      baseFlipInterval: 2.15,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.8,
      warningTime: 0.45,
      mazeSize: 23,
      devilEnabled: true,
      devilSpeedMultiplier: 1.33,
      devilSpawnDelay: 1.8,
      devilStepsPerSecond: 2.42,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    31: StageRule(
      stage: 31,
      name: 'Unstable Flow',
      playerSpeedMultiplier: 1.36,
      baseFlipInterval: 2.15,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.8,
      warningTime: 0.45,
      mazeSize: 23,
      devilEnabled: true,
      devilSpeedMultiplier: 1.34,
      devilSpawnDelay: 1.8,
      devilStepsPerSecond: 2.46,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    32: StageRule(
      stage: 32,
      name: 'Cut-Off',
      playerSpeedMultiplier: 1.38,
      baseFlipInterval: 2.05,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.7,
      warningTime: 0.45,
      mazeSize: 24,
      devilEnabled: true,
      devilSpeedMultiplier: 1.36,
      devilSpawnDelay: 1.7,
      devilStepsPerSecond: 2.52,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    33: StageRule(
      stage: 33,
      name: 'Dual Pressure',
      playerSpeedMultiplier: 1.39,
      baseFlipInterval: 2.05,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.7,
      warningTime: 0.45,
      mazeSize: 24,
      devilEnabled: true,
      devilSpeedMultiplier: 1.38,
      devilSpawnDelay: 1.7,
      devilStepsPerSecond: 2.58,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    34: StageRule(
      stage: 34,
      name: 'Distorted Reality',
      playerSpeedMultiplier: 1.40,
      baseFlipInterval: 1.95,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.6,
      warningTime: 0.45,
      mazeSize: 24,
      devilEnabled: true,
      devilSpeedMultiplier: 1.40,
      devilSpawnDelay: 1.6,
      devilStepsPerSecond: 2.64,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    35: StageRule(
      stage: 35,
      name: 'Breaking Point',
      playerSpeedMultiplier: 1.41,
      baseFlipInterval: 1.95,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.6,
      warningTime: 0.45,
      mazeSize: 24,
      devilEnabled: true,
      devilSpeedMultiplier: 1.41,
      devilSpawnDelay: 1.6,
      devilStepsPerSecond: 2.68,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    36: StageRule(
      stage: 36,
      name: 'Pressure Continuum',
      playerSpeedMultiplier: 1.42,
      baseFlipInterval: 1.9,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.6,
      warningTime: 0.45,
      mazeSize: 24,
      devilEnabled: true,
      devilSpeedMultiplier: 1.42,
      devilSpawnDelay: 1.6,
      devilStepsPerSecond: 2.72,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    37: StageRule(
      stage: 37,
      name: 'Prediction Lock',
      playerSpeedMultiplier: 1.43,
      baseFlipInterval: 1.9,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.6,
      warningTime: 0.45,
      mazeSize: 24,
      devilEnabled: true,
      devilSpeedMultiplier: 1.43,
      devilSpawnDelay: 1.6,
      devilStepsPerSecond: 2.76,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    38: StageRule(
      stage: 38,
      name: 'Distortion Stack',
      playerSpeedMultiplier: 1.44,
      baseFlipInterval: 1.85,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.5,
      warningTime: 0.45,
      mazeSize: 25,
      devilEnabled: true,
      devilSpeedMultiplier: 1.44,
      devilSpawnDelay: 1.5,
      devilStepsPerSecond: 2.80,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    39: StageRule(
      stage: 39,
      name: 'False Reality',
      playerSpeedMultiplier: 1.45,
      baseFlipInterval: 1.8,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.5,
      warningTime: 0.45,
      mazeSize: 25,
      devilEnabled: true,
      devilSpeedMultiplier: 1.45,
      devilSpawnDelay: 1.5,
      devilStepsPerSecond: 2.84,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    40: StageRule(
      stage: 40,
      name: 'Control Break',
      playerSpeedMultiplier: 1.46,
      baseFlipInterval: 1.8,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.5,
      warningTime: 0.45,
      mazeSize: 25,
      devilEnabled: true,
      devilSpeedMultiplier: 1.46,
      devilSpawnDelay: 1.5,
      devilStepsPerSecond: 2.88,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    41: StageRule(
      stage: 41,
      name: 'Pressure Reloaded',
      playerSpeedMultiplier: 1.47,
      baseFlipInterval: 1.8,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.5,
      warningTime: 0.45,
      mazeSize: 25,
      devilEnabled: true,
      devilSpeedMultiplier: 1.47,
      devilSpawnDelay: 1.5,
      devilStepsPerSecond: 2.92,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    42: StageRule(
      stage: 42,
      name: 'Hunted',
      playerSpeedMultiplier: 1.48,
      baseFlipInterval: 1.75,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.4,
      warningTime: 0.45,
      mazeSize: 25,
      devilEnabled: true,
      devilSpeedMultiplier: 1.48,
      devilSpawnDelay: 1.4,
      devilStepsPerSecond: 2.96,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    43: StageRule(
      stage: 43,
      name: 'Distortion Core',
      playerSpeedMultiplier: 1.49,
      baseFlipInterval: 1.75,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.4,
      warningTime: 0.45,
      mazeSize: 26,
      devilEnabled: true,
      devilSpeedMultiplier: 1.49,
      devilSpawnDelay: 1.4,
      devilStepsPerSecond: 3.0,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    44: StageRule(
      stage: 44,
      name: 'False Signals',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.7,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.4,
      warningTime: 0.45,
      mazeSize: 26,
      devilEnabled: true,
      devilSpeedMultiplier: 1.50,
      devilSpawnDelay: 1.4,
      devilStepsPerSecond: 3.04,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    45: StageRule(
      stage: 45,
      name: 'Dual Threat',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.7,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.4,
      warningTime: 0.45,
      mazeSize: 26,
      devilEnabled: true,
      devilSpeedMultiplier: 1.50,
      devilSpawnDelay: 1.4,
      devilStepsPerSecond: 3.08,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    46: StageRule(
      stage: 46,
      name: 'Collapse Flow',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.7,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.4,
      warningTime: 0.45,
      mazeSize: 26,
      devilEnabled: true,
      devilSpeedMultiplier: 1.50,
      devilSpawnDelay: 1.4,
      devilStepsPerSecond: 3.10,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    47: StageRule(
      stage: 47,
      name: 'No Escape',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.7,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.4,
      warningTime: 0.45,
      mazeSize: 26,
      devilEnabled: true,
      devilSpeedMultiplier: 1.50,
      devilSpawnDelay: 1.4,
      devilStepsPerSecond: 3.12,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    48: StageRule(
      stage: 48,
      name: 'Final Chaos',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.7,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.4,
      warningTime: 0.45,
      mazeSize: 26,
      devilEnabled: true,
      devilSpeedMultiplier: 1.50,
      devilSpawnDelay: 1.4,
      devilStepsPerSecond: 3.14,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    49: StageRule(
      stage: 49,
      name: 'Last Attempt',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.7,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.4,
      warningTime: 0.45,
      mazeSize: 26,
      devilEnabled: true,
      devilSpeedMultiplier: 1.50,
      devilSpawnDelay: 1.4,
      devilStepsPerSecond: 3.16,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    50: StageRule(
      stage: 50,
      name: 'Checkpoint Break',
      playerSpeedMultiplier: 1.45,
      baseFlipInterval: 2.5,
      flipRandomnessMin: 0.50,
      flipRandomnessMax: 0.50,
      firstFlipDelay: 2.6,
      warningTime: 0.60,
      mazeSize: 24,
      devilEnabled: true,
      devilSpeedMultiplier: 1.35,
      devilSpawnDelay: 2.6,
      devilStepsPerSecond: 2.40,
      devilSpawnDistanceCells: 4,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 1.6,
    ),
    51: StageRule(
      stage: 51,
      name: 'False Calm',
      playerSpeedMultiplier: 1.45,
      baseFlipInterval: 1.95,
      flipRandomnessMin: 0.60,
      flipRandomnessMax: 0.60,
      firstFlipDelay: 1.6,
      warningTime: 0.40,
      mazeSize: 24,
      devilEnabled: true,
      devilSpeedMultiplier: 1.43,
      devilSpawnDelay: 1.6,
      devilStepsPerSecond: 2.70,
      devilSpawnDistanceCells: 3,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    52: StageRule(
      stage: 52,
      name: 'Rebuild Threat',
      playerSpeedMultiplier: 1.46,
      baseFlipInterval: 1.85,
      flipRandomnessMin: 0.62,
      flipRandomnessMax: 0.62,
      firstFlipDelay: 1.5,
      warningTime: 0.40,
      mazeSize: 25,
      devilEnabled: true,
      devilSpeedMultiplier: 1.44,
      devilSpawnDelay: 1.5,
      devilStepsPerSecond: 2.76,
      devilSpawnDistanceCells: 2,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    53: StageRule(
      stage: 53,
      name: 'Route Control',
      playerSpeedMultiplier: 1.47,
      baseFlipInterval: 1.85,
      flipRandomnessMin: 0.65,
      flipRandomnessMax: 0.65,
      firstFlipDelay: 1.5,
      warningTime: 0.40,
      mazeSize: 25,
      devilEnabled: true,
      devilSpeedMultiplier: 1.45,
      devilSpawnDelay: 1.5,
      devilStepsPerSecond: 2.82,
      devilSpawnDistanceCells: 2,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    54: StageRule(
      stage: 54,
      name: 'Perception Break',
      playerSpeedMultiplier: 1.48,
      baseFlipInterval: 1.75,
      flipRandomnessMin: 0.67,
      flipRandomnessMax: 0.67,
      firstFlipDelay: 1.4,
      warningTime: 0.40,
      mazeSize: 25,
      devilEnabled: true,
      devilSpeedMultiplier: 1.46,
      devilSpawnDelay: 1.4,
      devilStepsPerSecond: 2.88,
      devilSpawnDistanceCells: 2,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    55: StageRule(
      stage: 55,
      name: 'Master Entry',
      playerSpeedMultiplier: 1.48,
      baseFlipInterval: 1.75,
      flipRandomnessMin: 0.68,
      flipRandomnessMax: 0.68,
      firstFlipDelay: 1.4,
      warningTime: 0.40,
      mazeSize: 25,
      devilEnabled: true,
      devilSpeedMultiplier: 1.47,
      devilSpawnDelay: 1.4,
      devilStepsPerSecond: 2.94,
      devilSpawnDistanceCells: 2,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    56: StageRule(
      stage: 56,
      name: 'Controlled Chaos',
      playerSpeedMultiplier: 1.49,
      baseFlipInterval: 1.75,
      flipRandomnessMin: 0.68,
      flipRandomnessMax: 0.68,
      firstFlipDelay: 1.4,
      warningTime: 0.40,
      mazeSize: 25,
      devilEnabled: true,
      devilSpeedMultiplier: 1.47,
      devilSpawnDelay: 1.4,
      devilStepsPerSecond: 2.98,
      devilSpawnDistanceCells: 2,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    57: StageRule(
      stage: 57,
      name: 'Trap Routes',
      playerSpeedMultiplier: 1.49,
      baseFlipInterval: 1.75,
      flipRandomnessMin: 0.70,
      flipRandomnessMax: 0.70,
      firstFlipDelay: 1.35,
      warningTime: 0.40,
      mazeSize: 25,
      devilEnabled: true,
      devilSpeedMultiplier: 1.48,
      devilSpawnDelay: 1.35,
      devilStepsPerSecond: 3.02,
      devilSpawnDistanceCells: 2,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    58: StageRule(
      stage: 58,
      name: 'Mind Loop',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.75,
      flipRandomnessMin: 0.70,
      flipRandomnessMax: 0.70,
      firstFlipDelay: 1.35,
      warningTime: 0.40,
      mazeSize: 26,
      devilEnabled: true,
      devilSpeedMultiplier: 1.49,
      devilSpawnDelay: 1.35,
      devilStepsPerSecond: 3.06,
      devilSpawnDistanceCells: 2,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    59: StageRule(
      stage: 59,
      name: 'Precision Lock',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.65,
      flipRandomnessMin: 0.72,
      flipRandomnessMax: 0.72,
      firstFlipDelay: 1.3,
      warningTime: 0.40,
      mazeSize: 26,
      devilEnabled: true,
      devilSpeedMultiplier: 1.49,
      devilSpawnDelay: 1.3,
      devilStepsPerSecond: 3.10,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    60: StageRule(
      stage: 60,
      name: 'Master Pressure',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.65,
      flipRandomnessMin: 0.72,
      flipRandomnessMax: 0.72,
      firstFlipDelay: 1.3,
      warningTime: 0.40,
      mazeSize: 26,
      devilEnabled: true,
      devilSpeedMultiplier: 1.50,
      devilSpawnDelay: 1.3,
      devilStepsPerSecond: 3.14,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    61: StageRule(
      stage: 61,
      name: 'Endurance Start',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.65,
      flipRandomnessMin: 0.72,
      flipRandomnessMax: 0.72,
      firstFlipDelay: 1.3,
      warningTime: 0.40,
      mazeSize: 26,
      devilEnabled: true,
      devilSpeedMultiplier: 1.49,
      devilSpawnDelay: 1.3,
      devilStepsPerSecond: 3.16,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    62: StageRule(
      stage: 62,
      name: 'Pattern Break',
      playerSpeedMultiplier: 1.51,
      baseFlipInterval: 1.65,
      flipRandomnessMin: 0.73,
      flipRandomnessMax: 0.73,
      firstFlipDelay: 1.3,
      warningTime: 0.40,
      mazeSize: 26,
      devilEnabled: true,
      devilSpeedMultiplier: 1.50,
      devilSpawnDelay: 1.3,
      devilStepsPerSecond: 3.20,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    63: StageRule(
      stage: 63,
      name: 'Mental Load',
      playerSpeedMultiplier: 1.51,
      baseFlipInterval: 1.65,
      flipRandomnessMin: 0.74,
      flipRandomnessMax: 0.74,
      firstFlipDelay: 1.3,
      warningTime: 0.40,
      mazeSize: 26,
      devilEnabled: true,
      devilSpeedMultiplier: 1.50,
      devilSpawnDelay: 1.3,
      devilStepsPerSecond: 3.24,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    64: StageRule(
      stage: 64,
      name: 'Fatigue Zone',
      playerSpeedMultiplier: 1.52,
      baseFlipInterval: 1.6,
      flipRandomnessMin: 0.74,
      flipRandomnessMax: 0.74,
      firstFlipDelay: 1.25,
      warningTime: 0.40,
      mazeSize: 27,
      devilEnabled: true,
      devilSpeedMultiplier: 1.51,
      devilSpawnDelay: 1.25,
      devilStepsPerSecond: 3.28,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    65: StageRule(
      stage: 65,
      name: 'Consistency Test',
      playerSpeedMultiplier: 1.52,
      baseFlipInterval: 1.6,
      flipRandomnessMin: 0.75,
      flipRandomnessMax: 0.75,
      firstFlipDelay: 1.25,
      warningTime: 0.40,
      mazeSize: 27,
      devilEnabled: true,
      devilSpeedMultiplier: 1.52,
      devilSpawnDelay: 1.25,
      devilStepsPerSecond: 3.32,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    66: StageRule(
      stage: 66,
      name: 'Pressure Sustain',
      playerSpeedMultiplier: 1.52,
      baseFlipInterval: 1.6,
      flipRandomnessMin: 0.75,
      flipRandomnessMax: 0.75,
      firstFlipDelay: 1.2,
      warningTime: 0.40,
      mazeSize: 27,
      devilEnabled: true,
      devilSpeedMultiplier: 1.51,
      devilSpawnDelay: 1.2,
      devilStepsPerSecond: 3.34,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    67: StageRule(
      stage: 67,
      name: 'Trap Memory',
      playerSpeedMultiplier: 1.52,
      baseFlipInterval: 1.6,
      flipRandomnessMin: 0.75,
      flipRandomnessMax: 0.75,
      firstFlipDelay: 1.2,
      warningTime: 0.40,
      mazeSize: 27,
      devilEnabled: true,
      devilSpeedMultiplier: 1.51,
      devilSpawnDelay: 1.2,
      devilStepsPerSecond: 3.36,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    68: StageRule(
      stage: 68,
      name: 'Dual Panic',
      playerSpeedMultiplier: 1.52,
      baseFlipInterval: 1.6,
      flipRandomnessMin: 0.75,
      flipRandomnessMax: 0.75,
      firstFlipDelay: 1.2,
      warningTime: 0.40,
      mazeSize: 27,
      devilEnabled: true,
      devilSpeedMultiplier: 1.52,
      devilSpawnDelay: 1.2,
      devilStepsPerSecond: 3.38,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    69: StageRule(
      stage: 69,
      name: 'Near Collapse',
      playerSpeedMultiplier: 1.52,
      baseFlipInterval: 1.6,
      flipRandomnessMin: 0.75,
      flipRandomnessMax: 0.75,
      firstFlipDelay: 1.2,
      warningTime: 0.40,
      mazeSize: 27,
      devilEnabled: true,
      devilSpeedMultiplier: 1.52,
      devilSpawnDelay: 1.2,
      devilStepsPerSecond: 3.40,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    70: StageRule(
      stage: 70,
      name: 'Pre-Breakpoint',
      playerSpeedMultiplier: 1.52,
      baseFlipInterval: 1.6,
      flipRandomnessMin: 0.75,
      flipRandomnessMax: 0.75,
      firstFlipDelay: 1.2,
      warningTime: 0.40,
      mazeSize: 27,
      devilEnabled: true,
      devilSpeedMultiplier: 1.52,
      devilSpawnDelay: 1.2,
      devilStepsPerSecond: 3.42,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    71: StageRule(
      stage: 71,
      name: 'Checkpoint Grind I',
      playerSpeedMultiplier: 1.52,
      baseFlipInterval: 1.7,
      flipRandomnessMin: 0.72,
      flipRandomnessMax: 0.72,
      firstFlipDelay: 1.3,
      warningTime: 0.40,
      mazeSize: 27,
      devilEnabled: true,
      devilSpeedMultiplier: 1.51,
      devilSpawnDelay: 1.3,
      devilStepsPerSecond: 3.30,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    72: StageRule(
      stage: 72,
      name: 'Checkpoint Grind II',
      playerSpeedMultiplier: 1.52,
      baseFlipInterval: 1.7,
      flipRandomnessMin: 0.72,
      flipRandomnessMax: 0.72,
      firstFlipDelay: 1.3,
      warningTime: 0.40,
      mazeSize: 27,
      devilEnabled: true,
      devilSpeedMultiplier: 1.51,
      devilSpawnDelay: 1.3,
      devilStepsPerSecond: 3.32,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    73: StageRule(
      stage: 73,
      name: 'Checkpoint Grind III',
      playerSpeedMultiplier: 1.52,
      baseFlipInterval: 1.7,
      flipRandomnessMin: 0.73,
      flipRandomnessMax: 0.73,
      firstFlipDelay: 1.3,
      warningTime: 0.40,
      mazeSize: 27,
      devilEnabled: true,
      devilSpeedMultiplier: 1.52,
      devilSpawnDelay: 1.3,
      devilStepsPerSecond: 3.34,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    74: StageRule(
      stage: 74,
      name: 'Checkpoint Grind IV',
      playerSpeedMultiplier: 1.52,
      baseFlipInterval: 1.7,
      flipRandomnessMin: 0.74,
      flipRandomnessMax: 0.74,
      firstFlipDelay: 1.3,
      warningTime: 0.40,
      mazeSize: 27,
      devilEnabled: true,
      devilSpeedMultiplier: 1.52,
      devilSpawnDelay: 1.3,
      devilStepsPerSecond: 3.36,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    75: StageRule(
      stage: 75,
      name: 'Checkpoint Break',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 2.35,
      flipRandomnessMin: 0.55,
      flipRandomnessMax: 0.55,
      firstFlipDelay: 2.4,
      warningTime: 0.50,
      mazeSize: 25,
      devilEnabled: true,
      devilSpeedMultiplier: 1.40,
      devilSpawnDelay: 2.4,
      devilStepsPerSecond: 2.55,
      devilSpawnDistanceCells: 4,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 1.8,
    ),
    76: StageRule(
      stage: 76,
      name: 'Extreme Skill I',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.75,
      flipRandomnessMin: 0.70,
      flipRandomnessMax: 0.70,
      firstFlipDelay: 1.3,
      warningTime: 0.40,
      mazeSize: 27,
      devilEnabled: true,
      devilSpeedMultiplier: 1.48,
      devilSpawnDelay: 1.3,
      devilStepsPerSecond: 3.20,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    77: StageRule(
      stage: 77,
      name: 'Extreme Skill II',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.75,
      flipRandomnessMin: 0.72,
      flipRandomnessMax: 0.72,
      firstFlipDelay: 1.3,
      warningTime: 0.40,
      mazeSize: 27,
      devilEnabled: true,
      devilSpeedMultiplier: 1.49,
      devilSpawnDelay: 1.3,
      devilStepsPerSecond: 3.24,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    78: StageRule(
      stage: 78,
      name: 'Pattern Hunt',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.65,
      flipRandomnessMin: 0.74,
      flipRandomnessMax: 0.74,
      firstFlipDelay: 1.25,
      warningTime: 0.40,
      mazeSize: 27,
      devilEnabled: true,
      devilSpeedMultiplier: 1.50,
      devilSpawnDelay: 1.25,
      devilStepsPerSecond: 3.28,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    79: StageRule(
      stage: 79,
      name: 'Route Pressure',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.65,
      flipRandomnessMin: 0.75,
      flipRandomnessMax: 0.75,
      firstFlipDelay: 1.25,
      warningTime: 0.40,
      mazeSize: 28,
      devilEnabled: true,
      devilSpeedMultiplier: 1.50,
      devilSpawnDelay: 1.25,
      devilStepsPerSecond: 3.32,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    80: StageRule(
      stage: 80,
      name: 'End Of Certainty',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.65,
      flipRandomnessMin: 0.76,
      flipRandomnessMax: 0.76,
      firstFlipDelay: 1.25,
      warningTime: 0.40,
      mazeSize: 28,
      devilEnabled: true,
      devilSpeedMultiplier: 1.50,
      devilSpawnDelay: 1.25,
      devilStepsPerSecond: 3.36,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    81: StageRule(
      stage: 81,
      name: 'Mental Pressure I',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.65,
      flipRandomnessMin: 0.76,
      flipRandomnessMax: 0.76,
      firstFlipDelay: 1.25,
      warningTime: 0.40,
      mazeSize: 28,
      devilEnabled: true,
      devilSpeedMultiplier: 1.50,
      devilSpawnDelay: 1.25,
      devilStepsPerSecond: 3.38,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    82: StageRule(
      stage: 82,
      name: 'Mental Pressure II',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.65,
      flipRandomnessMin: 0.77,
      flipRandomnessMax: 0.77,
      firstFlipDelay: 1.25,
      warningTime: 0.40,
      mazeSize: 28,
      devilEnabled: true,
      devilSpeedMultiplier: 1.50,
      devilSpawnDelay: 1.25,
      devilStepsPerSecond: 3.40,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    83: StageRule(
      stage: 83,
      name: 'Loop Trap',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.55,
      flipRandomnessMin: 0.78,
      flipRandomnessMax: 0.78,
      firstFlipDelay: 1.2,
      warningTime: 0.40,
      mazeSize: 28,
      devilEnabled: true,
      devilSpeedMultiplier: 1.49,
      devilSpawnDelay: 1.2,
      devilStepsPerSecond: 3.42,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    84: StageRule(
      stage: 84,
      name: 'Do Not Panic',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.55,
      flipRandomnessMin: 0.78,
      flipRandomnessMax: 0.78,
      firstFlipDelay: 1.2,
      warningTime: 0.40,
      mazeSize: 28,
      devilEnabled: true,
      devilSpeedMultiplier: 1.49,
      devilSpawnDelay: 1.2,
      devilStepsPerSecond: 3.44,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    85: StageRule(
      stage: 85,
      name: 'Mental Wall',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.55,
      flipRandomnessMin: 0.79,
      flipRandomnessMax: 0.79,
      firstFlipDelay: 1.2,
      warningTime: 0.40,
      mazeSize: 28,
      devilEnabled: true,
      devilSpeedMultiplier: 1.49,
      devilSpawnDelay: 1.2,
      devilStepsPerSecond: 3.46,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    86: StageRule(
      stage: 86,
      name: 'Precision Hell I',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.55,
      flipRandomnessMin: 0.79,
      flipRandomnessMax: 0.79,
      firstFlipDelay: 1.2,
      warningTime: 0.40,
      mazeSize: 28,
      devilEnabled: true,
      devilSpeedMultiplier: 1.50,
      devilSpawnDelay: 1.2,
      devilStepsPerSecond: 3.48,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    87: StageRule(
      stage: 87,
      name: 'Precision Hell II',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.55,
      flipRandomnessMin: 0.79,
      flipRandomnessMax: 0.79,
      firstFlipDelay: 1.2,
      warningTime: 0.40,
      mazeSize: 28,
      devilEnabled: true,
      devilSpeedMultiplier: 1.49,
      devilSpawnDelay: 1.2,
      devilStepsPerSecond: 3.49,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    88: StageRule(
      stage: 88,
      name: 'Accuracy Tax',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.5,
      flipRandomnessMin: 0.80,
      flipRandomnessMax: 0.80,
      firstFlipDelay: 1.15,
      warningTime: 0.40,
      mazeSize: 28,
      devilEnabled: true,
      devilSpeedMultiplier: 1.49,
      devilSpawnDelay: 1.15,
      devilStepsPerSecond: 3.50,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    89: StageRule(
      stage: 89,
      name: 'Needle Run',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.45,
      flipRandomnessMin: 0.80,
      flipRandomnessMax: 0.80,
      firstFlipDelay: 1.1,
      warningTime: 0.40,
      mazeSize: 28,
      devilEnabled: true,
      devilSpeedMultiplier: 1.49,
      devilSpawnDelay: 1.1,
      devilStepsPerSecond: 3.51,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    90: StageRule(
      stage: 90,
      name: 'Precision Crown',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.45,
      flipRandomnessMin: 0.80,
      flipRandomnessMax: 0.80,
      firstFlipDelay: 1.1,
      warningTime: 0.40,
      mazeSize: 28,
      devilEnabled: true,
      devilSpeedMultiplier: 1.50,
      devilSpawnDelay: 1.1,
      devilStepsPerSecond: 3.52,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    91: StageRule(
      stage: 91,
      name: 'Mind Break I',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.45,
      flipRandomnessMin: 0.80,
      flipRandomnessMax: 0.80,
      firstFlipDelay: 1.1,
      warningTime: 0.40,
      mazeSize: 28,
      devilEnabled: true,
      devilSpeedMultiplier: 1.50,
      devilSpawnDelay: 1.1,
      devilStepsPerSecond: 3.53,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    92: StageRule(
      stage: 92,
      name: 'Mind Break II',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.45,
      flipRandomnessMin: 0.80,
      flipRandomnessMax: 0.80,
      firstFlipDelay: 1.1,
      warningTime: 0.40,
      mazeSize: 28,
      devilEnabled: true,
      devilSpeedMultiplier: 1.49,
      devilSpawnDelay: 1.1,
      devilStepsPerSecond: 3.54,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    93: StageRule(
      stage: 93,
      name: 'Instinct Route',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.45,
      flipRandomnessMin: 0.80,
      flipRandomnessMax: 0.80,
      firstFlipDelay: 1.1,
      warningTime: 0.40,
      mazeSize: 28,
      devilEnabled: true,
      devilSpeedMultiplier: 1.49,
      devilSpawnDelay: 1.1,
      devilStepsPerSecond: 3.55,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    94: StageRule(
      stage: 94,
      name: 'Blind Discipline',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.45,
      flipRandomnessMin: 0.80,
      flipRandomnessMax: 0.80,
      firstFlipDelay: 1.1,
      warningTime: 0.40,
      mazeSize: 28,
      devilEnabled: true,
      devilSpeedMultiplier: 1.49,
      devilSpawnDelay: 1.1,
      devilStepsPerSecond: 3.56,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    95: StageRule(
      stage: 95,
      name: 'Nerve Lock',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.45,
      flipRandomnessMin: 0.80,
      flipRandomnessMax: 0.80,
      firstFlipDelay: 1.1,
      warningTime: 0.40,
      mazeSize: 28,
      devilEnabled: true,
      devilSpeedMultiplier: 1.50,
      devilSpawnDelay: 1.1,
      devilStepsPerSecond: 3.57,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    96: StageRule(
      stage: 96,
      name: 'Final Trial I',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.45,
      flipRandomnessMin: 0.80,
      flipRandomnessMax: 0.80,
      firstFlipDelay: 1.1,
      warningTime: 0.40,
      mazeSize: 28,
      devilEnabled: true,
      devilSpeedMultiplier: 1.49,
      devilSpawnDelay: 1.1,
      devilStepsPerSecond: 3.58,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    97: StageRule(
      stage: 97,
      name: 'Final Trial II',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.45,
      flipRandomnessMin: 0.80,
      flipRandomnessMax: 0.80,
      firstFlipDelay: 1.1,
      warningTime: 0.40,
      mazeSize: 28,
      devilEnabled: true,
      devilSpeedMultiplier: 1.50,
      devilSpawnDelay: 1.1,
      devilStepsPerSecond: 3.59,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    98: StageRule(
      stage: 98,
      name: 'Final Trial III',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.45,
      flipRandomnessMin: 0.80,
      flipRandomnessMax: 0.80,
      firstFlipDelay: 1.1,
      warningTime: 0.40,
      mazeSize: 28,
      devilEnabled: true,
      devilSpeedMultiplier: 1.50,
      devilSpawnDelay: 1.1,
      devilStepsPerSecond: 3.60,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    99: StageRule(
      stage: 99,
      name: 'Final Trial IV',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.45,
      flipRandomnessMin: 0.80,
      flipRandomnessMax: 0.80,
      firstFlipDelay: 1.1,
      warningTime: 0.40,
      mazeSize: 28,
      devilEnabled: true,
      devilSpeedMultiplier: 1.50,
      devilSpawnDelay: 1.1,
      devilStepsPerSecond: 3.61,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
    100: StageRule(
      stage: 100,
      name: 'THE BREAKER',
      playerSpeedMultiplier: 1.50,
      baseFlipInterval: 1.6,
      flipRandomnessMin: 0.70,
      flipRandomnessMax: 0.80,
      firstFlipDelay: 1.8,
      warningTime: 0.40,
      mazeSize: 29,
      devilEnabled: true,
      devilSpeedMultiplier: 1.48,
      devilSpawnDelay: 1.0,
      devilStepsPerSecond: 3.62,
      devilSpawnDistanceCells: 1,
      safeZoneCount: 2,
      safeZoneDurationSeconds: 0.0,
    ),
  };

  static StageRule forStage(int stage) {
    final clamped = stage.clamp(1, maxDefinedStage);
    final baseRule = _rules[clamped]!;
    if (!baseRule.devilEnabled) {
      return baseRule;
    }

    final targetDevilMultiplier =
        (baseRule.playerSpeedMultiplier - _devilPlayerSpeedDelta).clamp(
          0.01,
          baseRule.playerSpeedMultiplier,
        );
    if ((baseRule.devilSpeedMultiplier - targetDevilMultiplier).abs() <
        0.000001) {
      return baseRule;
    }

    return StageRule(
      stage: baseRule.stage,
      name: baseRule.name,
      playerSpeedMultiplier: baseRule.playerSpeedMultiplier,
      baseFlipInterval: baseRule.baseFlipInterval,
      flipRandomnessMin: baseRule.flipRandomnessMin,
      flipRandomnessMax: baseRule.flipRandomnessMax,
      firstFlipDelay: baseRule.firstFlipDelay,
      warningTime: baseRule.warningTime,
      mazeSize: baseRule.mazeSize,
      devilEnabled: baseRule.devilEnabled,
      devilSpeedMultiplier: targetDevilMultiplier,
      devilSpawnDelay: baseRule.devilSpawnDelay,
      devilStepsPerSecond: baseRule.devilStepsPerSecond,
      devilSpawnDistanceCells: baseRule.devilSpawnDistanceCells,
      safeZoneCount: baseRule.safeZoneCount,
      safeZoneDurationSeconds: baseRule.safeZoneDurationSeconds,
    );
  }
}
