// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHtpdoKYLDLIi0EhNJJxFgLbrzvA8e35M',
    appId: '1:158165984868:web:a1ec057032689454e86171',
    messagingSenderId: '158165984868',
    projectId: 'fearflip-179cf',
    authDomain: 'fearflip-179cf.firebaseapp.com',
    storageBucket: 'fearflip-179cf.firebasestorage.app',
    measurementId: 'G-XVFR8FXR3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqBP0XF5hhuCojR_tZHbh9O3VFyJk_UPw',
    appId: '1:158165984868:android:1b2ca17d58d0b7dae86171',
    messagingSenderId: '158165984868',
    projectId: 'fearflip-179cf',
    storageBucket: 'fearflip-179cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmzwDoDSrGfyukFfOdCk-Q6yRheRC3dg0',
    appId: '1:158165984868:ios:b7294b3ddd50142de86171',
    messagingSenderId: '158165984868',
    projectId: 'fearflip-179cf',
    storageBucket: 'fearflip-179cf.firebasestorage.app',
    iosBundleId: 'com.yourcompany.fearflip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmzwDoDSrGfyukFfOdCk-Q6yRheRC3dg0',
    appId: '1:158165984868:ios:b7294b3ddd50142de86171',
    messagingSenderId: '158165984868',
    projectId: 'fearflip-179cf',
    storageBucket: 'fearflip-179cf.firebasestorage.app',
    iosBundleId: 'com.yourcompany.fearflip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHtpdoKYLDLIi0EhNJJxFgLbrzvA8e35M',
    appId: '1:158165984868:web:e7a9e2c4d03ed280e86171',
    messagingSenderId: '158165984868',
    projectId: 'fearflip-179cf',
    authDomain: 'fearflip-179cf.firebaseapp.com',
    storageBucket: 'fearflip-179cf.firebasestorage.app',
    measurementId: 'G-1ELVBL1YDV',
  );
}
